"""empty message

Revision ID: 3b0a02825e97
Revises: a4aa90cd909e
Create Date: 2024-11-11 23:28:43.440660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0a02825e97'
down_revision = 'a4aa90cd909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
