"""empty message

Revision ID: abd13bae28e7
Revises: 3b0a02825e97
Create Date: 2024-11-11 23:30:49.731709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd13bae28e7'
down_revision = '3b0a02825e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
